# file: roles/php70/tasks/install.yml

- name: Install epel from remote repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

- name: Install remi from remote repo
  yum: name=http://rpms.remirepo.net/enterprise/remi-release-7.rpm state=present

- name: upgrade all packages
  yum: name=* state=latest

- name: Install php
  yum: pkg={{ item }} enablerepo=remi,remi-php71 state=present
  with_items:
    - php

- name: Install php modules
  yum: pkg={{ item }} enablerepo=remi,remi-php71 state=present
  with_items:
    - php-mbstring
    - php-devel
    - php-opcache
    - php-soap
    - php-pdo
    - php-json
    - php-zip
    - php-xmlrpc
    - php-mcrypt
    - php-pecl-xdebug
    - php-xml
    - php-mysql
    - php-gd
    - php-fpm
    - php-common
  notify:
  - restart nginx

- name: Change default php-fpm config
  copy: src=config_templates/php-fpm-default.tpl dest=/etc/php-fpm.d/www.conf
#   # template: src=templates/php-fpm-default.tpl dest=/etc/php-fpm.d/www.conf
